apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
  namespace: todo-app
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service-server
          image: {{ .Values.image.apiservice }}
          ports:
            - containerPort: 8000
          env:
            - name: AUTH_SERVICE_URL
              value: auth-service:3000
            - name: TODO_SERVICE_URL
              value: todo-service:3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: todo-app
  labels:
    app: api-service
spec:
  type: ClusterIP
  selector:
    app: api-service
  ports:
    - port: 8000
      targetPort: 8000
