apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: auth-database-secret
  namespace: todo-app
data:
  db_name: YXV0aGRi
  username: dG9kb19kYl91c2Vy
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-database-pv-volume
  namespace: todo-app
  labels:
    type: local
    app: auth-database
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/authdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-database-pv-claim
  namespace: todo-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-database-deployment
  namespace: todo-app
  labels:
    app: auth-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-database
  template:
    metadata:
      labels:
        app: auth-database
    spec:
      volumes:
        - name: auth-database-pv-storage
          persistentVolumeClaim:
            claimName: auth-database-pv-claim
      containers:
        - name: auth-database
          image: postgres:11
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-database-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auth-database-secret
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: auth-database-secret
                  key: db_name
            - name: PGDATA
              value: /var/lib/postgresql/data
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: auth-database-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: auth-database-service
  namespace: todo-app
  labels:
    app: auth-database
spec:
  selector:
    app: auth-database
  ports:
    - port: 5432
      targetPort: 5432
