apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
  namespace: todo-app
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service-server
          image: heyanoop/todo-api:1.0
          ports:
            - containerPort: 8000
          env:
            - name: AUTH_SERVICE_URL
              value: auth-service:3000
            - name: TODO_SERVICE_URL
              value: todo-service:3000